"""
Django settings for djangoprojectbase project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def cargar_env(ruta_env):
    if not ruta_env.exists():
        return

    for linea in ruta_env.read_text(encoding="utf-8").splitlines():
        linea = linea.strip()
        if not linea or linea.startswith("#") or "=" not in linea:
            continue

        nombre, valor = linea.split("=", 1)
        nombre = nombre.strip()
        valor = valor.strip().strip('"').strip("'")

        if nombre:
            os.environ.setdefault(nombre, valor)


cargar_env(BASE_DIR / ".env")


def env_bool(nombre, defecto=False):
    valor = os.environ.get(nombre)
    if valor is None:
        return defecto
    return valor.strip().lower() in {"1", "true", "yes", "on", "si"}


def env_int(nombre, defecto):
    valor = os.environ.get(nombre)
    if valor in (None, ""):
        return defecto
    return int(valor)


def env_list(nombre, defecto=None):
    valor = os.environ.get(nombre)
    if valor in (None, ""):
        return defecto or []
    return [item.strip() for item in valor.split(",") if item.strip()]


def env_path(nombre, defecto):
    valor = os.environ.get(nombre)
    return Path(valor) if valor else defecto


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-dev-only")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool("DJANGO_DEBUG", True)

ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'widget_tweaks',
    'sga.apps.SgaConfig',
    'sga.documentos.apps.DocumentosConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoprojectbase.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoprojectbase.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql_psycopg2'),
        'NAME': os.environ.get('DB_NAME', 'uteq'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD', 'pass123'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    },
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Guayaquil'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Configuracion requerida por el modulo de gestion de documentos legales.
FLASK_PDF_DIR = env_path(
    'FLASK_PDF_DIR',
    BASE_DIR / 'Prototipo_Version_Django' / 'media' / 'documentos',
)
IA_DOCUMENTOS_BASE_URL = os.environ.get('IA_DOCUMENTOS_BASE_URL', 'http://localhost:8000')
IA_DOCUMENTOS_ANALIZAR_PATH = os.environ.get(
    'IA_DOCUMENTOS_ANALIZAR_PATH',
    '/api/integracion/documentos/analizar/',
)
IA_DOCUMENTOS_TIMEOUT = env_int('IA_DOCUMENTOS_TIMEOUT', 120)
IA_SSL_VERIFY = env_bool('IA_SSL_VERIFY', True)
IA_DOCUMENTOS_REINTENTO_ESPERA = env_int('IA_DOCUMENTOS_REINTENTO_ESPERA', 300)
IA_DOCUMENTOS_PORCENTAJE_TEXTO_MINIMO = env_int('IA_DOCUMENTOS_PORCENTAJE_TEXTO_MINIMO', 80)
IA_CHROMA_BASE_URL = os.environ.get('IA_CHROMA_BASE_URL', IA_DOCUMENTOS_BASE_URL)
IA_CHROMA_GUARDAR_PATH = os.environ.get(
    'IA_CHROMA_GUARDAR_PATH',
    '/api/integracion/documentos/guardar-chroma/',
)
IA_CHROMA_QUITAR_VIGENCIA_PATH = os.environ.get(
    'IA_CHROMA_QUITAR_VIGENCIA_PATH',
    '/api/integracion/documentos/quitar-vigencia/',
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
