-- Ejecutar una sola vez sobre bases de datos existentes.
CREATE TABLE IF NOT EXISTS public.historial_eliminaciones (
    id_historial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento bigint NOT NULL,
    id_version bigint,
    titulo_documento text NOT NULL,
    numero_version integer,
    nombre_usuario text NOT NULL,
    motivo_eliminacion text NOT NULL,
    total_versiones integer NOT NULL CHECK (total_versiones > 0),
    versiones_eliminadas jsonb NOT NULL DEFAULT '[]'::jsonb,
    fecha_eliminacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE public.historial_eliminaciones
    ADD COLUMN IF NOT EXISTS versiones_eliminadas jsonb NOT NULL DEFAULT '[]'::jsonb;

CREATE INDEX IF NOT EXISTS idx_historial_eliminaciones_fecha
    ON public.historial_eliminaciones (fecha_eliminacion DESC);
