# Generated by Django 5.2.16 on 2026-07-23 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('puede_modificar_', 'Descripción del permiso'),),
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('nombres', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('apellido1', models.CharField(default='', max_length=50, verbose_name='1er Apellido')),
                ('apellido2', models.CharField(default='', max_length=50, verbose_name='2do Apellido')),
                ('cedula', models.CharField(blank=True, default='', max_length=20, verbose_name='Cedula')),
                ('pasaporte', models.CharField(blank=True, default='', max_length=20, verbose_name='Pasaporte')),
                ('ruc', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Ruc')),
                ('nacimiento', models.DateField(verbose_name='Fecha de nacimiento o constitución')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
                'abstract': False,
            },
        ),
    ]
