# Generated by Django 5.2.16 on 2026-07-23 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sga', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_modificacion', models.DateTimeField(blank=True, null=True)),
                ('url', models.CharField(default='', max_length=100, verbose_name='URL')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('icono', models.CharField(default='', max_length=100, verbose_name='Icono')),
                ('descripcion', models.CharField(default='', max_length=200, verbose_name='Descripción')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sga', models.BooleanField(default=False, verbose_name='Activo para SGA')),
                ('sagest', models.BooleanField(default=False, verbose_name='Activo para SAGEST')),
                ('posgrado', models.BooleanField(default=False, verbose_name='Activo para POSGRADO')),
                ('postulacion', models.BooleanField(default=False, verbose_name='Activo para Postulción')),
                ('usuario_creacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['nombre'],
                'unique_together': {('url',)},
            },
        ),
    ]
