from django.db import migrations, models


CREAR_TABLAS_DOCUMENTALES = """
CREATE TABLE IF NOT EXISTS public.docs (
    id_documento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    titulo text NOT NULL,
    descripcion text,
    id_version_vigente bigint,
    creado_por bigint,
    fecha_creacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    actualizado_por bigint,
    fecha_actualizacion timestamp with time zone,
    eliminado_por bigint,
    fecha_eliminacion timestamp with time zone,
    motivo_eliminacion text,
    palabras_clave text NOT NULL DEFAULT '',
    tipo varchar(20) NOT NULL DEFAULT 'Documento legal',
    tiene_versionamiento boolean NOT NULL DEFAULT false,
    uuid_documento uuid NOT NULL DEFAULT gen_random_uuid(),
    CONSTRAINT chk_docs_tipo CHECK (
        tipo IN ('Documento legal', 'Manual', 'Reglamento', 'Guías',
                 'Ordenes', 'Modelos', 'Procedimiento', 'Videos')
    )
);

CREATE TABLE IF NOT EXISTS public.doc_versions (
    id_version bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento bigint NOT NULL,
    numero_version integer NOT NULL,
    archivo_nombre text NOT NULL,
    archivo_path text NOT NULL,
    archivo_tipo varchar(100),
    archivo_tamano bigint,
    descripcion_cambio text,
    mensaje_auditoria text,
    fecha_subida timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subido_por bigint,
    fecha_aprobacion timestamp with time zone NOT NULL,
    uuid_version uuid NOT NULL DEFAULT gen_random_uuid(),
    estado text NOT NULL DEFAULT 'BORRADOR',
    estado_ia text NOT NULL DEFAULT 'PENDIENTE',
    porcentaje_texto_ia numeric(5, 2),
    mensaje_ia text,
    fecha_analisis_ia timestamp with time zone,
    resultado_ia jsonb,
    publicado boolean NOT NULL DEFAULT false,
    eliminado_por bigint,
    fecha_eliminacion timestamp with time zone,
    motivo_eliminacion text,
    CONSTRAINT chk_numero_version CHECK (numero_version > 0),
    CONSTRAINT ck_doc_versions_estado CHECK (
        estado IN ('BORRADOR', 'VIGENTE', 'NO_VIGENTE', 'ELIMINADO')
    ),
    CONSTRAINT ck_doc_versions_estado_ia CHECK (
        estado_ia IN ('PENDIENTE', 'LEIDO', 'OMITIDO', 'OBSERVADO', 'ERROR')
    ),
    CONSTRAINT uq_doc_version_numero UNIQUE (id_documento, numero_version),
    CONSTRAINT fk_doc_versions_docs FOREIGN KEY (id_documento)
        REFERENCES public.docs(id_documento) ON UPDATE CASCADE ON DELETE RESTRICT
);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_docs_version_vigente'
          AND conrelid = 'public.docs'::regclass
    ) THEN
        ALTER TABLE public.docs ADD CONSTRAINT fk_docs_version_vigente
            FOREIGN KEY (id_version_vigente) REFERENCES public.doc_versions(id_version)
            ON UPDATE CASCADE ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.documento_acceso (
    id_acceso bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento bigint NOT NULL,
    id_perfil_externo bigint,
    id_grupo_externo bigint,
    id_tipo_periodo_externo bigint,
    activo boolean NOT NULL DEFAULT true,
    asignado_por bigint,
    fecha_asignacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_documento_acceso UNIQUE (
        id_documento, id_perfil_externo, id_grupo_externo, id_tipo_periodo_externo
    ),
    CONSTRAINT fk_documento_acceso_docs FOREIGN KEY (id_documento)
        REFERENCES public.docs(id_documento) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.documento_lectura (
    id_lectura bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento bigint NOT NULL,
    id_version bigint,
    id_usuario_externo bigint,
    nombre_usuario text,
    accion varchar(30) NOT NULL,
    fecha_hora timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_documento_lectura_accion CHECK (
        accion IN ('LECTURA', 'PREVISUALIZACION', 'DESCARGA')
    ),
    CONSTRAINT fk_documento_lectura_docs FOREIGN KEY (id_documento)
        REFERENCES public.docs(id_documento) ON UPDATE CASCADE ON DELETE CASCADE,
    CONSTRAINT fk_documento_lectura_version FOREIGN KEY (id_version)
        REFERENCES public.doc_versions(id_version) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS public.historial_eliminaciones (
    id_historial bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_documento bigint NOT NULL,
    id_version bigint,
    titulo_documento text NOT NULL,
    numero_version integer,
    nombre_usuario text NOT NULL,
    motivo_eliminacion text NOT NULL,
    total_versiones integer NOT NULL CHECK (total_versiones > 0),
    versiones_eliminadas jsonb NOT NULL DEFAULT '[]'::jsonb,
    fecha_eliminacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS public.modulo_editores (
    id_editor bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario_externo bigint NOT NULL UNIQUE,
    nombre_usuario text,
    activo boolean NOT NULL DEFAULT true,
    asignado_por bigint,
    fecha_asignacion timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_doc_versions_id_documento
    ON public.doc_versions (id_documento);
CREATE INDEX IF NOT EXISTS ix_doc_versions_estado
    ON public.doc_versions (estado);
CREATE INDEX IF NOT EXISTS ix_doc_versions_estado_ia
    ON public.doc_versions (estado_ia);
CREATE UNIQUE INDEX IF NOT EXISTS uq_doc_versions_uuid_version
    ON public.doc_versions (uuid_version);
CREATE UNIQUE INDEX IF NOT EXISTS uq_docs_uuid_documento
    ON public.docs (uuid_documento);
CREATE INDEX IF NOT EXISTS idx_docs_titulo
    ON public.docs USING gin (to_tsvector('spanish', titulo));
CREATE INDEX IF NOT EXISTS idx_docs_descripcion
    ON public.docs USING gin (to_tsvector('spanish', descripcion));
CREATE INDEX IF NOT EXISTS idx_documento_acceso_id_documento
    ON public.documento_acceso (id_documento);
CREATE INDEX IF NOT EXISTS idx_documento_acceso_segmento
    ON public.documento_acceso (
        id_perfil_externo, id_grupo_externo, id_tipo_periodo_externo
    );
CREATE INDEX IF NOT EXISTS idx_documento_lectura_documento
    ON public.documento_lectura (id_documento);
CREATE INDEX IF NOT EXISTS idx_documento_lectura_accion
    ON public.documento_lectura (accion);
CREATE INDEX IF NOT EXISTS idx_historial_eliminaciones_fecha
    ON public.historial_eliminaciones (fecha_eliminacion DESC);
"""


def crear_tablas_documentales(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(CREAR_TABLAS_DOCUMENTALES)


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccesoDocumento",
            fields=[
                ("id_acceso", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_perfil_externo", models.BigIntegerField(blank=True, null=True)),
                ("id_grupo_externo", models.BigIntegerField(blank=True, null=True)),
                ("id_tipo_periodo_externo", models.BigIntegerField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("asignado_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_asignacion", models.DateTimeField()),
            ],
            options={"db_table": "documento_acceso", "managed": False},
        ),
        migrations.CreateModel(
            name="Documento",
            fields=[
                ("id_documento", models.BigAutoField(primary_key=True, serialize=False)),
                ("titulo", models.TextField()),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("creado_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_creacion", models.DateTimeField()),
                ("actualizado_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_actualizacion", models.DateTimeField(blank=True, null=True)),
                ("eliminado_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_eliminacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_eliminacion", models.TextField(blank=True, null=True)),
                ("palabras_clave", models.TextField(default="")),
                ("tipo", models.CharField(default="Documento legal", max_length=20)),
                ("tiene_versionamiento", models.BooleanField(default=False)),
                ("uuid_documento", models.UUIDField()),
            ],
            options={"db_table": "docs", "managed": False},
        ),
        migrations.CreateModel(
            name="EditorModulo",
            fields=[
                ("id_editor", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_usuario_externo", models.BigIntegerField(unique=True)),
                ("nombre_usuario", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                ("asignado_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_asignacion", models.DateTimeField()),
            ],
            options={"db_table": "modulo_editores", "managed": False},
        ),
        migrations.CreateModel(
            name="HistorialEliminacion",
            fields=[
                ("id_historial", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_documento", models.BigIntegerField()),
                ("id_version", models.BigIntegerField(blank=True, null=True)),
                ("titulo_documento", models.TextField()),
                ("numero_version", models.IntegerField(blank=True, null=True)),
                ("nombre_usuario", models.TextField()),
                ("motivo_eliminacion", models.TextField()),
                ("total_versiones", models.IntegerField()),
                ("versiones_eliminadas", models.JSONField(default=list)),
                ("fecha_eliminacion", models.DateTimeField()),
            ],
            options={
                "db_table": "historial_eliminaciones",
                "ordering": ("-fecha_eliminacion", "-id_historial"),
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LecturaDocumento",
            fields=[
                ("id_lectura", models.BigAutoField(primary_key=True, serialize=False)),
                ("id_usuario_externo", models.BigIntegerField(blank=True, null=True)),
                ("nombre_usuario", models.TextField(blank=True, null=True)),
                ("accion", models.CharField(max_length=30)),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
            ],
            options={"db_table": "documento_lectura", "managed": False},
        ),
        migrations.CreateModel(
            name="VersionDocumento",
            fields=[
                ("id_version", models.BigAutoField(primary_key=True, serialize=False)),
                ("numero_version", models.IntegerField()),
                ("archivo_nombre", models.TextField()),
                ("archivo_path", models.TextField()),
                ("archivo_tipo", models.CharField(blank=True, max_length=100, null=True)),
                ("archivo_tamano", models.BigIntegerField(blank=True, null=True)),
                ("descripcion_cambio", models.TextField(blank=True, null=True)),
                ("mensaje_auditoria", models.TextField(blank=True, null=True)),
                ("fecha_subida", models.DateTimeField()),
                ("subido_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_aprobacion", models.DateTimeField()),
                ("uuid_version", models.UUIDField()),
                ("estado", models.TextField(default="BORRADOR")),
                ("estado_ia", models.TextField(default="PENDIENTE")),
                ("porcentaje_texto_ia", models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ("mensaje_ia", models.TextField(blank=True, null=True)),
                ("fecha_analisis_ia", models.DateTimeField(blank=True, null=True)),
                ("resultado_ia", models.JSONField(blank=True, null=True)),
                ("publicado", models.BooleanField(default=False)),
                ("eliminado_por", models.BigIntegerField(blank=True, null=True)),
                ("fecha_eliminacion", models.DateTimeField(blank=True, null=True)),
                ("motivo_eliminacion", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "doc_versions",
                "ordering": ("-numero_version", "-id_version"),
                "managed": False,
            },
        ),
        migrations.RunPython(crear_tablas_documentales, migrations.RunPython.noop),
    ]
